xzgrep security patch xzgrep-ZDI-CAN-16587
AnacondaRecipes/xz-feedstock pull request #4
Opened 2022-04-28 18:56 UTC by cbouss

# Changes

Changes:
- Update metadata (https, license)
- Bump build number
- Add security patch xzgrep-ZDI-CAN-16587
  See: https://tukaani.org/xz/ https://www.mail-archive.com/xz-devel@tukaani.org/msg00551.html

# Review Information

## Source

https://git.tukaani.org/

## License

https://git.tukaani.org/?p=xz.git;a=blob_plain;f=COPYING;hb=HEAD

## Upstream Changes

Security patch as explained here: https://tukaani.org/xz/ 

## Issues

NA

## Pins and Requireds

NA

## Testing

Existing tests passed.

# Closing Comments

xz 5.2.5 patched with xzgrep-ZDI-CAN-16587

2022-04-28 21:32 UTC, cbouss commented
prefect failed to download source

2022-04-29 16:31 UTC, cbouss commented
concourse: https://concourse.build.corp.continuum.io/teams/main/pipelines/cb-xzgrep

2022-04-29 17:02 UTC, katietz requested changes
otherwise looks great

2022-04-29 17:02 UTC, katietz commented on recipe/meta.yaml
Please do not add empty lines here

2022-04-29 17:02 UTC, katietz commented on recipe/meta.yaml
> -    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
please don't remove those tests.  instead add as requirement 'conda-build' package.  that will fix this test

2022-04-29 17:08 UTC, cbouss commented on recipe/meta.yaml
> -    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
Anthony was saying this was replaced by calling --error-overlinking --error-overdepending. Is not the case?

2022-04-29 17:55 UTC, cbouss commented on recipe/meta.yaml
> -    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
not necessarily true since this is not enabled by default

2022-04-29 18:32 UTC, ScottBailey approved these changes

2022-05-02 14:10 UTC, varlackc reviewed
We might need to add the license family to the meta.yaml file
https://github.com/AnacondaRecipes/xz-feedstock/blob/cb_xzgrep_5.2.5_b1/recipe/meta.yaml#L58&&L60

also there seems to be an issue building the package in `prefect` for `osx-64`
https://cloud.prefect.io/anaconda/flow-run/3c87658a-94ee-41a3-8cb5-67f27a9f32c1

other than that the package looks good, we just have to solve those issues and then we can approve the package.

2022-05-02 15:36 UTC, cbouss commented
Updated license family. linux-ppc64le is still failing, but again due to sourceforge failed download.

2022-05-03 15:02 UTC, katietz approved these changes
thanks for adding this conda-build requirement for the inspect.

2022-05-03 18:20 UTC, merged